Repository Pennyw0rth/NetExec, pull requests merged in 2023-11, with the labels that each got.

#50 Implement s4u abuse
  nxc/connection.py
  nxc/protocols/smb.py
  nxc/protocols/smb/kerberos.py
  nxc/protocols/smb/proto_args.py
  tests/e2e_commands.txt
Labels: enhancement, tested, reviewed code

#63 [connection.py] Improvement
  nxc/connection.py
  nxc/protocols/ftp.py
  nxc/protocols/ldap.py
  nxc/protocols/mssql.py
  nxc/protocols/rdp.py
  nxc/protocols/smb.py
  nxc/protocols/ssh.py
  nxc/protocols/vnc.py
  nxc/protocols/wmi.py
Labels: enhancement, bug-fix, tested, reviewed code

#88 Improve bloodhound connector with Netbios domain name
  .github/ISSUE_TEMPLATE/bug_report.md
  nxc/connection.py
  nxc/helpers/bloodhound.py
Labels: bug-fix, tested, reviewed code

#90 Set computer accounts as owned in bloodhound if local admin privs
  nxc/helpers/bloodhound.py
  nxc/protocols/ldap.py
  nxc/protocols/mssql.py
  nxc/protocols/rdp.py
  nxc/protocols/smb.py
  nxc/protocols/winrm.py
Labels: enhancement, tested

#72 [winrm] Improvement
  nxc/protocols/winrm.py
  nxc/protocols/winrm/proto_args.py
  tests/e2e_commands.txt
Labels: enhancement, bug-fix, tested, reviewed code

#108 Fix: update MS17-010 for Python3 properly; add debug logging
  nxc/modules/ms17-010.py
Labels: bug-fix, tested

#107 [winrm] disable logger & add miss port args
  nxc/protocols/winrm.py
Labels: enhancement, reviewed code

#111 Fix Kerberoasting for #104
  nxc/protocols/ldap.py
  nxc/protocols/ldap/kerberos.py
  nxc/protocols/ldap/proto_args.py
Labels: tested

#109 Improve module texts
  nxc/modules/daclread.py
  nxc/modules/laps.py
  nxc/modules/scan-network.py
  nxc/modules/spider_plus.py
Labels: documentation

#113 [ssh] fix #112
  nxc/protocols/ssh.py
Labels: bug-fix, tested, reviewed code

#106 disable use of ssh_agent
  nxc/protocols/ssh.py
Labels: bug-fix, reviewed code

#115 Adding error handling for unexpected powershell output, see issue #93
  nxc/modules/veeam_dump.py
Labels: bug-fix

#116 Netexec v1.1.0
  README.md
  nxc/cli.py
  pyproject.toml
Labels: documentation

#120 tests: improve output of e2e tests for errors
  tests/e2e_test.py
Labels: bug-fix, reviewed code

#119 fix(smb errors): getErrorString only returns one item, not a tuple
  nxc/protocols/smb.py
Labels: bug-fix

#128 Add New Ldap Flag --active-users
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
Labels: enhancement
