Repository Pennyw0rth/NetExec, pull requests merged in 2023-09, with the labels that each got.

#2 Fix for allowing to test multiple users with one password
  cme/connection.py
Labels: bug-fix

#11 Update README.md for NetExec rename
  README.md
Labels: documentation

#13 Add CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#16 Fix CLI
  .github/workflows/crackmapexec-test.yml
  .github/workflows/crackmapexec.yml
Labels: bug-fix

#7 Make some text more precise
  cme/cli.py
  cme/modules/veeam_dump.py
  cme/protocols/smb.py
  cme/protocols/smb/atexec.py
  cme/protocols/smb/mmcexec.py
  cme/protocols/smb/proto_args.py
  cme/protocols/smb/smbexec.py
  cme/protocols/smb/wmiexec.py
  cme/protocols/wmi.py
  cme/protocols/wmi/proto_args.py
  cme/protocols/wmi/wmiexec.py
  cme/protocols/wmi/wmiexec_event.py
Labels: documentation

#9 [winrm] less ugly if condition
  cme/protocols/winrm.py
Labels: enhancement

#4 [wmi] bug fix in 'check_admin' function
  cme/protocols/wmi.py
  poetry.lock
Labels: bug-fix

#12 Update LICENSE for NetExec
  LICENSE
Labels: documentation

#29 fix webdav module exception handler
  nxc/modules/webdav.py
Labels: bug-fix

#26 Windows Build for NetExec
  .gitignore
  netexec.spec
  nxc/.hooks/hook-pypykatz.py
  nxc/modules/drop-sc.py
  nxc/modules/nanodump.py
  nxc/modules/procdump.py
Labels: enhancement

#27 Update Github Build Actions for Releases
  .github/workflows/netexec.yml
Labels: enhancement

#43 Fix #42, --dc-list crashes on ldap with logging enabled
  nxc/protocols/ldap.py
Labels: bug-fix

#24 Add README text
  README.md
Labels: documentation

#44 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#45 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
