Repository Pennyw0rth/NetExec, pull requests merged in 2023-12, with the labels that each got.

#137 Fix bug in WCC module
  nxc/modules/wcc.py
Labels: tested, reviewed code

#114 [winrm] better output
  nxc/protocols/winrm.py
Labels: bug-fix, tested, reviewed code

#146 Fix: iis module cmd exec quotes
  nxc/modules/appcmd.py
Labels: bug-fix, tested, reviewed code

#133 Modules enumeration ldap
  nxc/modules/get-unixUserPassword.py
  nxc/modules/get-userPassword.py
Labels: new module, tested, reviewed code

#141 Restructure how laps login works to fix login issues
  nxc/connection.py
  nxc/logger.py
  nxc/protocols/ldap/laps.py
  nxc/protocols/smb.py
  nxc/protocols/winrm.py
Labels: bug-fix, tested

#150 Remove domain DN from ldap query, fixes #144
  nxc/modules/trust.py
Labels: bug-fix, tested, reviewed code

#130 Fixing binaries for RDP and WINRM
  .github/workflows/build-binaries.yml
  .github/workflows/build-zipapps.yml
  .gitignore
  netexec.spec
Labels: bug-fix, reviewed code

#132 Removing deprec…
  nxc/protocols/smb.py
Labels: bug-fix, reviewed code

#148 add argcomplete bash/zsh completion
  README.md
  nxc/cli.py
  nxc/loaders/moduleloader.py
  nxc/modules/MAQ.py
  nxc/modules/add-computer.py
  nxc/modules/enum_trusts.py
  nxc/modules/get-network.py
  nxc/modules/group-mem.py
  nxc/modules/iis.py
  nxc/modules/ioxidresolver.py
  nxc/modules/lsassy.py
  nxc/modules/user-desc.py
  nxc/modules/veeam.py
  nxc/modules/wifi.py
  nxc/modules/winscp.py
  poetry.lock
  pyproject.toml
Labels: enhancement, tested, reviewed code

#155 Fixing module name check with windows backspace path
  nxc/loaders/moduleloader.py
Labels: bug-fix, windows
