Repository Pennyw0rth/NetExec, pull requests merged in 2023-10, with the labels that each got.

#49 Fix #48 tries to falsly add creds to bloodhound using --laps
  nxc/protocols/smb.py
Labels: bug-fix

#58 Update enum_av.py
  nxc/modules/enum_av.py
Labels: enhancement, tested

#54 Create schtask.py
  nxc/modules/schtask_as.py
Labels: new module, tested

#67 [nanodump] fix error with temporary path
  nxc/modules/nanodump.py
Labels: bug-fix

#30 Update dependencies (including impacket fork) for v1.1.0
  poetry.lock
  pyproject.toml
Labels: enhancement, tested, reviewed code

#80 mpgn is back 🎉
  .github/CODEOWNERS
  LICENSE
  README.md
Labels: enhancement

#40 Enhancing the FTP protocol
  nxc/protocols/ftp.py
  nxc/protocols/ftp/proto_args.py
  tests/data/test_file.txt
  tests/e2e_commands.txt
Labels: enhancement, good first issue, tested, reviewed code

#74 Add module sorting
  nxc/loaders/moduleloader.py
  nxc/netexec.py
Labels: enhancement

#25 [ssh] improvement
  nxc/protocols/ssh.py
  nxc/protocols/ssh/proto_args.py
  tests/e2e_commands.txt
Labels: enhancement, tested, reviewed code

#87 fix(dependencies): add bloodhound to netexec.spec, fixes #79
  netexec.spec
Labels: reviewed code

#86 Downgrade termcolor to prevent atty check which disables colors
  poetry.lock
  pyproject.toml
Labels: bug-fix

#89 Add python version and OS info to debug output
  nxc/netexec.py
Labels: enhancement

#94 Update README.md - one grammatical error.
  README.md
Labels: documentation

#98 Fix import error on windows
  nxc/netexec.py
Labels: bug-fix

#97 fix typos in python files of directory `nxc/modules`
  nxc/modules/daclread.py
  nxc/modules/example_module.py
  nxc/modules/keepass_trigger.py
  nxc/modules/ldap-checker.py
  nxc/modules/scan-network.py
  nxc/modules/schtask_as.py
  nxc/modules/teams_localdb.py
  nxc/modules/user_desc.py
Labels: documentation
