Repository Pennyw0rth/NetExec, pull requests merged in 2024-08, with the labels that each got.

#390 Fix admin check in mssql_priv
  nxc/modules/mssql_priv.py
Labels: bug-fix

#391 Fix: module spider_plus with filtered folders
  nxc/modules/spider_plus.py
Labels: bug-fix

#386 Adding SCCM LDAP Reconnaissance to NetExec
  nxc/modules/sccm.py
  nxc/parsers/ldap_results.py
  nxc/protocols/smb.py
Labels: new module

#392 Fix spider_plus bug where len was applied to the count not an array
  nxc/modules/spider_plus.py
  nxc/netexec.py
Labels: bug-fix

#374 Add module to lookup hostname of Hyper-V host - 'hyperv-host.py'
  nxc/modules/hyperv-host.py
Labels: new module, reviewed code

#399 Add Unix availability to README.md
  README.md
Labels: documentation

#408 ldap-checker.py false positive fixed
  nxc/modules/ldap-checker.py
Labels: bug-fix

#409 ldap-checker.py Catch connection errors
  nxc/modules/ldap-checker.py
Labels: bug-fix

#328 Identify Pre-Created Computer Accounts
  nxc/modules/pre2k.py
Labels: new module
