Repository Pennyw0rth/NetExec, pull requests merged in 2024-10, with the labels that each got.

#366 New Protocol NFS
  nxc/connection.py
  nxc/protocols/nfs.py
  nxc/protocols/nfs/__init__.py
  nxc/protocols/nfs/database.py
  nxc/protocols/nfs/db_navigator.py
  nxc/protocols/nfs/proto_args.py
  poetry.lock
  pyproject.toml
  tests/e2e_commands.txt
Labels: enhancement

#433 Fix a bug with the databases when a new protocol is added
  nxc/database.py
Labels: bug-fix

#404 Add file write check on smb
  nxc/protocols/smb.py
Labels: bug-fix

#434 Fix pwned label when brute forcing with guest account enabled
  nxc/protocols/smb.py
Labels: bug-fix

#435 Improve test suite
  nxc/connection.py
  nxc/protocols/nfs/proto_args.py
  tests/e2e_commands.txt
  tests/e2e_tests.py
Labels: bug-fix, tests

#411 Increase plaintext&hash login speeds
  nxc/protocols/smb.py
Labels: enhancement

#300 Add coerce_plus Module
  nxc/modules/coerce_plus.py
  nxc/modules/dfscoerce.py
  nxc/modules/petitpotam.py
  nxc/modules/printerbug.py
  nxc/modules/shadowcoerce.py
  tests/e2e_commands.txt
Labels: enhancement, new module, tested, reviewed code

#400 refactoring to fix InterfaceError of DB
  nxc/database.py
  nxc/protocols/ftp/database.py
  nxc/protocols/ldap/database.py
  nxc/protocols/mssql/database.py
  nxc/protocols/nfs/database.py
  nxc/protocols/rdp/database.py
  nxc/protocols/smb/database.py
  nxc/protocols/ssh/database.py
  nxc/protocols/vnc/database.py
  nxc/protocols/winrm/database.py
Labels: enhancement, bug-fix

#442 Small fixes for coerce_plus
  nxc/modules/coerce_plus.py
Labels: bug-fix

#440 Updated the --get-file method to get large files from NFS shares
  nxc/protocols/nfs.py
Labels: bug-fix

#447 Fix module loading for ssh, vnc and ftp
  nxc/protocols/ftp.py
  nxc/protocols/ssh.py
  nxc/protocols/vnc.py
Labels: bug-fix

#446 Fix windows and encoding stuff
  netexec.spec
  nxc/logger.py
  nxc/parsers/ldap_results.py
Labels: bug-fix, windows

#448 Release v1.3.0
  nxc/cli.py
  pyproject.toml
Labels: documentation

#458 Fix runasppl.py
  nxc/modules/runasppl.py
Labels: bug-fix

#466 Fixed issue with --options flag
  nxc/netexec.py
Labels: bug-fix

#460 Drop support for Python 3.8 and 3.9
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-binaries.yml
  .github/workflows/build-zipapps.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.md
  nxc/logger.py
  nxc/netexec.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#473 Code and stability improvements
  nxc/connection.py
  nxc/protocols/ftp.py
  nxc/protocols/ldap.py
  nxc/protocols/mssql.py
  nxc/protocols/nfs.py
  nxc/protocols/rdp.py
  nxc/protocols/smb.py
  nxc/protocols/ssh.py
  nxc/protocols/winrm.py
  nxc/protocols/wmi.py
Labels: bug-fix, refactor

#474 fix(nfs): check if status is 13 and print out permission denied for share
  nxc/protocols/nfs.py
Labels: bug-fix
