Repository Pennyw0rth/NetExec, pull requests merged in 2024-11, with the labels that each got.

#462 [SMB] Add --enum-shares options like in NFS protocol
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
Labels: enhancement

#405 Mssql xp_cmdshell added "is enabled" check
  nxc/protocols/mssql/mssqlexec.py
Labels: enhancement, bug-fix

#486 Fix nmap XML parser when looking for ftp service
  nxc/parsers/nmap.py
Labels: bug-fix

#481 schtask_as - Delete task when there is an error
  nxc/modules/schtask_as.py
  nxc/protocols/smb/atexec.py
Labels: bug-fix

#487 Fix veeam output
  .github/PULL_REQUEST_TEMPLATE.md
  nxc/modules/veeam.py
Labels: bug-fix

#381 New LDAP Flag Find Delegation
  nxc/parsers/ldap_results.py
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
Labels: enhancement

#438 Bugfix : exec-method specified in module file is not used
  nxc/helpers/args.py
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
Labels: bug-fix

#380 add an option to ioxidresolver to get only IP values different than targets
  nxc/modules/ioxidresolver.py
Labels: enhancement

#488 Allow for empty domains
  nxc/protocols/smb.py
Labels: bug-fix

#498 Speed improvements and bug fixes
  nxc/logger.py
  nxc/protocols/smb.py
Labels: enhancement, bug-fix
