Repository Pennyw0rth/NetExec, pull requests merged in 2024-03, with the labels that each got.

#191 [lib] Improve ntlm_parser.py
  nxc/helpers/ntlm_parser.py
  nxc/protocols/winrm.py
  nxc/protocols/wmi.py
Labels: enhancement

#136 [MSSQL] Improvement
  nxc/modules/nanodump.py
  nxc/protocols/mssql.py
  nxc/protocols/mssql/mssqlexec.py
  nxc/protocols/mssql/proto_args.py
Labels: enhancement, tested

#190 Update connection.py to force login
  nxc/connection.py
Labels: enhancement, tested

#171 Remove pyreadline as it causes errors in nxcdb
  poetry.lock
  pyproject.toml
Labels: bug-fix

#202 Update neo4j python driver
  poetry.lock
  pyproject.toml
Labels: dependencies

#204 Fix string escaping issues for Kali package, fix some logging, and allow for lsa and sam WinRM dumping
  nxc/cli.py
  nxc/modules/daclread.py
  nxc/modules/get-desc-users.py
  nxc/modules/masky.py
  nxc/modules/met_inject.py
  nxc/modules/ms17-010.py
  nxc/modules/runasppl.py
  nxc/modules/wcc.py
  nxc/protocols/smb/samrfunc.py
  nxc/protocols/winrm.py
  nxc/protocols/winrm/proto_args.py
Labels: reviewed code

#41 Extract obsolete operating systems from LDAP
  nxc/modules/obsolete.py
Labels: new module, tested, reviewed code

#206 fix(wcc.py): properly escape for #200
  nxc/modules/wcc.py
Labels: bug-fix

#65 Create get_fgpp.py
  nxc/modules/pso.py
  poetry.lock
  pyproject.toml
  tests/e2e_commands.txt
Labels: new module, tested

#163 [Module] printerbug
  nxc/modules/printerbug.py
Labels: new module, tested, reviewed code

#212 Adding the fileNamePrefix which was introduced in bloodhound so files…
  nxc/protocols/ldap.py
  nxc/protocols/ldap/bloodhound.py
Labels: bug-fix

#213 Stop Netexec from adding null auth user to bloodhound
  nxc/protocols/ldap.py
  nxc/protocols/mssql.py
  nxc/protocols/rdp.py
  nxc/protocols/smb.py
  nxc/protocols/winrm.py
Labels: bug-fix

#214 Fix SMB users lookup and return last password set date
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
  nxc/protocols/smb/samruser.py
Labels: bug-fix

#220 Fix: module names 8-10 chars being cut off
  nxc/logger.py
Labels: bug-fix

#215 Update LDAP users lookup to match SMB
  nxc/parsers/ldap_results.py
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
  nxc/protocols/smb.py
Labels: enhancement

#226 BloodHound & hash_spider fixes
  nxc/data/nxc.conf
  nxc/helpers/bloodhound.py
  nxc/modules/hash_spider.py
Labels: bug-fix

#216 [ldap-checker] Module fix
  nxc/modules/ldap-checker.py
Labels: bug-fix, tested

#218 Fixing antivirus enumeration
  nxc/modules/enum_av.py
  nxc/netexec.py
Labels: bug-fix

#224 Update LDAP active users lookup to match SMB
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
Labels: enhancement

#152 Several LDAP improvements
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
  nxc/protocols/mssql.py
  nxc/protocols/smb.py
  nxc/protocols/winrm.py
  nxc/protocols/wmi.py
Labels: enhancement, bug-fix

#222 Make loggedon-users unique to reduce spam and fix alignment
  nxc/protocols/smb.py
Labels: enhancement

#227 Several ldap bug fixes
  nxc/protocols/ldap.py
Labels: bug-fix

#229 Logging fixes (double logging & function caller obfuscation)
  nxc/logger.py
Labels: bug-fix

#238 rename MAQ.py to maq.py
  nxc/loaders/moduleloader.py
  nxc/modules/maq.py
  nxc/netexec.py
Labels: bug-fix

#230 Fix testing and linting
  .github/workflows/lint.yml
  .github/workflows/test.yml
  tests/README.md
  tests/e2e_tests.py
Labels: documentation

#240 Small QOL changes
  .github/workflows/test.yml
  nxc/connection.py
Labels: enhancement
