Repository Pennyw0rth/NetExec, pull requests merged in 2024-02, with the labels that each got.

#167 Hotfix: Allow broader version for argcomplete to fix macos installations
  poetry.lock
  pyproject.toml
Labels: bug-fix

#123 nxcdb: refactor shared database/workspace setup code & allow for creation/setting of workspaces outside of nxcdb interactive console
  nxc/database.py
  nxc/first_run.py
  nxc/netexec.py
  nxc/nxcdb.py
  nxc/paths.py
  tests/test_smb_database.py
Labels: enhancement, tested, reviewed code

#179 Allow a single word as audit mode "character"
  nxc/config.py
Labels: enhancement

#185 Remove unnecessary remote ops check
  nxc/protocols/smb.py
Labels: bug-fix

#176 Add error handling for protocol level
  nxc/netexec.py
Labels: enhancement

#173 Update ntlmv1.py
  nxc/modules/ntlmv1.py
Labels: bug-fix, tested, reviewed code

#186 Fix audit_mode in ldap
  nxc/protocols/ldap.py
Labels: bug-fix

#160 [Module] Enum ADCS Certificate Authority without creds.
  nxc/modules/enum_ca.py
Labels: new module, reviewed code

#172 [winrm] say goodbye to SMB
  nxc/helpers/ntlm_parser.py
  nxc/protocols/winrm.py
  nxc/protocols/winrm/proto_args.py
Labels: enhancement, tested, reviewed code
