Repository Pennyw0rth/NetExec, pull requests merged in 2024-04, with the labels that each got.

#236 Winlogon Autologon module
  nxc/modules/reg-winlogon.py
Labels: new module

#235 fix --users for LDAP proto
  nxc/protocols/ldap.py
Labels: bug-fix

#242 Neff qol the second
  nxc/cli.py
  nxc/connection.py
  nxc/netexec.py
Labels: enhancement

#126 --kerberoast Improvement
  nxc/protocols/ldap.py
Labels: enhancement

#239 Add git commit to version command
  nxc/cli.py
  nxc/logger.py
  nxc/netexec.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#246 Add verbosity to dpapi, so the user knows if no secrets were found
  nxc/protocols/smb.py
Labels: enhancement

#237 bugfixes: add-computer & nanodump modules
  nxc/modules/add-computer.py
  nxc/modules/nanodump.py
Labels: bug-fix

#251 fixed one grammar error repeated in several files
  nxc/protocols/ftp/database.py
  nxc/protocols/ldap/database.py
  nxc/protocols/mssql/database.py
  nxc/protocols/rdp/database.py
  nxc/protocols/smb/database.py
  nxc/protocols/ssh/database.py
  nxc/protocols/vnc/database.py
  nxc/protocols/winrm/database.py
  nxc/protocols/wmi/database.py
Labels: documentation

#254 Fix ssh authentication with encrypted ssh file
  nxc/protocols/ssh.py
Labels: bug-fix

#255 Update Slinky module
  nxc/modules/slinky.py
Labels: enhancement

#259 Fix computers enum
  nxc/protocols/smb.py
Labels: bug-fix

#270 ldap-checker: fix for Python 3.12 compatibility
  nxc/modules/ldap-checker.py
Labels: bug-fix

#272 Fix ssh auth message
  nxc/protocols/ssh.py
Labels: bug-fix

#277 fix mssql_priv
  nxc/modules/adcs.py
  nxc/modules/daclread.py
  nxc/modules/mssql_priv.py
  nxc/modules/nanodump.py
  nxc/modules/user-desc.py
Labels: bug-fix

#271 Fixing #263
  nxc/protocols/ldap.py
  nxc/protocols/ldap/kerberos.py
Labels: bug-fix, tested

#250 Fix bug where modules would be the same object across protocols
  nxc/connection.py
  nxc/netexec.py
Labels: bug-fix

#269 Updating dependencies
  nxc/modules/daclread.py
  poetry.lock
  pyproject.toml
Labels: bug-fix, dependencies, tested

#283 Add feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#285 Fix #284
  netexec.spec
Labels: bug-fix
