Repository Pennyw0rth/NetExec, pull requests merged in 2024-12, with the labels that each got.

#311 Timeroast module
  nxc/modules/timeroast.py
Labels: new module

#499 Bugfix: file extension filter of spiderplus was misleading/broken
  nxc/modules/spider_plus.py
Labels: bug-fix

#502 Fix RDP '--nla-screenshot' option
  nxc/protocols/rdp.py
Labels: bug-fix

#500 Fix TARGET_DN object query
  nxc/modules/daclread.py
Labels: bug-fix

#503 Add baseDN flag to ldap
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
Labels: bug-fix

#492 Add rid-brute flag to mssql protocol
  nxc/protocols/mssql.py
  nxc/protocols/mssql/proto_args.py
  tests/e2e_commands.txt
Labels: new module

#456 Add mssql_coerce Module
  nxc/modules/mssql_coerce.py
Labels: new module

#449 [SMB] Powershell history module rework
  nxc/modules/powershell_history.py
Labels: enhancement

#451 [SMB] Rework the runasppl module
  nxc/modules/runasppl.py
Labels: enhancement

#444 [SMB] Add the Notepad++ module
  nxc/modules/notepad++.py
Labels: new module

#415 Added new modules for mssql- namely enum_impersonate, enum_logins,, enum_links, exec_on_link, link_enable_xp, link_xpcmd
  nxc/modules/enum_impersonate.py
  nxc/modules/enum_links.py
  nxc/modules/enum_logins.py
  nxc/modules/exec_on_link.py
  nxc/modules/link_enable_xp.py
  nxc/modules/link_xpcmd.py
Labels: new module

#510 fix trust relation for smb
  nxc/protocols/smb.py
Labels: bug-fix

#508 Remove smb from ldap proto
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
Labels: enhancement

#511 fix trust relation for ldap
  nxc/protocols/ldap.py
Labels: bug-fix

#368 Add new SMB module to download Screenshots created by Snipping Tool
  nxc/modules/snipped.py
Labels: new module

#515 Change error to fail message
  nxc/modules/mssql_coerce.py
Labels: enhancement

#516 Add a query for the linked server config if we are local admin
  nxc/modules/enum_links.py
Labels: enhancement

#520 Rename ldapConnection to the new ldap_connection var #508 #4767762 - Fix Modules
  nxc/modules/adcs.py
  nxc/modules/daclread.py
  nxc/modules/enum_trusts.py
  nxc/modules/find-computer.py
  nxc/modules/get-desc-users.py
  nxc/modules/get-network.py
  nxc/modules/get-unixUserPassword.py
  nxc/modules/get-userPassword.py
  nxc/modules/group-mem.py
  nxc/modules/groupmembership.py
  nxc/modules/obsolete.py
  nxc/modules/pre2k.py
  nxc/modules/pso.py
  nxc/modules/sccm.py
  nxc/modules/subnets.py
  nxc/modules/user-desc.py
  nxc/modules/whoami.py
Labels: bug-fix

#522 Fix #514
  nxc/connection.py
Labels: bug-fix

#523 [SMB] Allow force to disable SMBv1
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
  tests/e2e_commands.txt
Labels: enhancement, bug-fix

#521 [Module] Add remove mic check
  nxc/modules/remove-mic.py
  tests/e2e_commands.txt
Labels: new module

#526 Fix user-desc.py
  nxc/modules/user-desc.py
Labels: bug-fix

#528 Show error messages when rdp fails
  nxc/protocols/rdp.py
  nxc/protocols/smb.py
Labels: enhancement
