Repository Pennyw0rth/NetExec, pull requests merged in 2024-01, with the labels that each got.

#162 Fix some issues in deps
  poetry.lock
  pyproject.toml
Labels: dependencies, tested, reviewed code

#135 Fix issue #134 with tempfile on windows
  nxc/protocols/smb/firefox.py
Labels: bug-fix, requires testing, windows, reviewed code

#139 Surpress any errors when using rdp and broken python version
  nxc/protocols/rdp.py
Labels: bug-fix, requires testing, reviewed code

#153 Fix usernames with empty spaces in ntds dump
  nxc/protocols/smb.py
Labels: bug-fix, reviewed code
