Repository Pennyw0rth/NetExec, pull requests merged in 2024-09, with the labels that each got.

#393 Fix issues with kerberos and non NTLM domains
  nxc/connection.py
  nxc/protocols/ldap/laps.py
Labels: bug-fix

#306 Module wcc added some defender checks
  nxc/modules/wcc.py
Labels: enhancement

#342 schtask_as Improvement - Options for custom task, file, and location.
  nxc/modules/schtask_as.py
Labels: enhancement, reviewed code

#407 Smbghost scanning module
  nxc/modules/smbghost.py
Labels: new module

#417 Make --version switch universal so help2man will work properly
  nxc/cli.py
Labels: documentation

#418 Encode delegate/impersonate user name string as utf8 unicode, not latin1
  nxc/protocols/smb/kerberos.py
Labels: bug-fix

#423 Small cosmetic fix for ldap when using --no-smb
  nxc/protocols/ldap.py
Labels: bug-fix

#341 Add new SMB module to get the PowerShell history on all the users
  nxc/modules/powershell_history.py
Labels: new module, tested, reviewed code

#406 Fix file logging for display messages
  nxc/logger.py
Labels: enhancement, bug-fix
