Repository Pennyw0rth/NetExec, pull requests merged in 2024-05, with the labels that each got.

#290 Reduce third party debug logging
  nxc/logger.py
Labels: enhancement

#297 Feat: Allow for running specific e2e tests by line number
  tests/e2e_tests.py
Labels: enhancement

#282 #281 - Multi-file put/get for smb
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
Labels: enhancement

#291 Change jitter option to throttle authentications
  nxc/cli.py
  nxc/connection.py
  nxc/netexec.py
  tests/e2e_commands.txt
Labels: enhancement

#299 Create Pull Request Template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: documentation, enhancement

#249 Add PuTTY module and fix WinSCP
  nxc/modules/example_module.py
  nxc/modules/putty.py
  nxc/modules/winscp.py
Labels: bug-fix, new module

#308 Fix: hash_spider Lsassy Parser syntax
  .gitignore
  nxc/modules/hash_spider.py
Labels: bug-fix

#310 fix: move PR template to the correct location
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation, bug-fix

#314 Fix for tests referencing files, password/username variable, and a couple KERBEROS space issues
  tests/e2e_commands.txt
  tests/e2e_tests.py
Labels: bug-fix

#313 Handle paramiko error when bruteforcing
  nxc/protocols/ssh.py
Labels: bug-fix, dependencies

#296 Refactor/fix/update PowerShell and related features
  nxc/helpers/powershell.py
  nxc/modules/met_inject.py
  nxc/protocols/mssql.py
  nxc/protocols/mssql/mssqlexec.py
  nxc/protocols/mssql/proto_args.py
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
  nxc/protocols/smb/wmiexec.py
  tests/data/test_amsi_bypass.txt
  tests/e2e_commands.txt
  tests/e2e_tests.py
Labels: enhancement, bug-fix, reviewed code, refactor

#307 Fix: WCC Module - do not create log file on every file load
  nxc/modules/wcc.py
  nxc/protocols/smb.py
Labels: bug-fix

#317 Improving execution speed and misc command execution improvements
  nxc/cli.py
  nxc/protocols/smb/atexec.py
  nxc/protocols/smb/mmcexec.py
  nxc/protocols/smb/proto_args.py
  nxc/protocols/smb/smbexec.py
  nxc/protocols/smb/wmiexec.py
  tests/e2e_commands.txt
Labels: enhancement

#309 Add ldap query option
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
Labels: enhancement

#321 Refactor argparse options
  nxc/cli.py
  nxc/helpers/args.py
  nxc/protocols/ftp/proto_args.py
  nxc/protocols/ldap/proto_args.py
  nxc/protocols/mssql/proto_args.py
  nxc/protocols/rdp/proto_args.py
  nxc/protocols/smb/proto_args.py
  nxc/protocols/ssh/proto_args.py
  nxc/protocols/vnc/proto_args.py
  nxc/protocols/winrm/proto_args.py
  nxc/protocols/wmi/proto_args.py
  tests/e2e_commands.txt
Labels: enhancement, bug-fix

#325 Added --dns-tcp,--dns-timeout and --dns-server parameters to the ldap protocol when using --bloodhound
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
Labels: enhancement

#326 Windows Fixes for v1.2
  netexec.spec
  nxc/modules/pi.py
  nxc/modules/procdump.py
  nxc/modules/schtask_as.py
  nxc/modules/slinky.py
  nxc/modules/spider_plus.py
  nxc/modules/teams_localdb.py
  nxc/netexec.py
  nxc/paths.py
  nxc/protocols/smb/smbexec.py
  tests/README.md
  tests/e2e_commands.txt
  tests/e2e_tests.py
Labels: bug-fix, windows
