Repository Pennyw0rth/NetExec, pull requests merged in 2024-06, with the labels that each got.

#279 fix extract_password
  nxc/modules/keepass_trigger.py
Labels: bug-fix

#334 [NXCDB] Add support for CTRL-D
  nxc/nxcdb.py
Labels: enhancement

#333 Add output if a successful authentication is via Guest privileges
  nxc/connection.py
  nxc/protocols/smb.py
  tests/data/test_hashes.txt
Labels: enhancement

#336 add testing hash file to e2e_commands.txt
  tests/e2e_commands.txt
Labels: tests

#340 Improve OS detection
  nxc/protocols/smb.py
Labels: enhancement, bug-fix, tested, reviewed code

#343 Adding some logger when users have been dumped
  nxc/protocols/ldap.py
  nxc/protocols/smb/samruser.py
Labels: enhancement

#345 Added domain name for --users with samr
  nxc/protocols/smb/samruser.py
Labels: enhancement

#344 Add EnumAV Detection for Cortex XDR
  nxc/modules/enum_av.py
Labels: enhancement

#293 Adding module to retrieve network interfaces info
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
Labels: enhancement, Waiting for response

#286 New SMB/WMI Module BitLocker
  nxc/modules/bitlocker.py
  tests/e2e_commands.txt
Labels: new module

#356 Fix #332 - Add exception handling to prevent crashes against linux hosts
  nxc/protocols/smb.py
Labels: bug-fix
