Repository Pennyw0rth/NetExec, pull requests merged in 2025-02, with the labels that each got.

#542 Fix lsass Dump Files Deleting Process When Dump Fail
  nxc/modules/handlekatz.py
  nxc/modules/nanodump.py
  nxc/modules/procdump.py
Labels: bug-fix

#541 Updated exe files while putting for evasion
  nxc/modules/handlekatz.py
  nxc/modules/impersonate.py
  nxc/modules/nanodump.py
  nxc/modules/pi.py
  nxc/modules/procdump.py
Labels: enhancement

#552 [smb] Always delete service when using smbexec
  nxc/protocols/smb/smbexec.py
Labels: bug-fix

#537 Add Backup operators module
  nxc/modules/backup_operator.py
  tests/e2e_commands.txt
Labels: new module

#441 Update users and active-users against anonymous ldap authentication
  nxc/protocols/ldap.py
Labels: enhancement, bug-fix

#560 Fix hardcoded option
  nxc/protocols/mssql/mssqlexec.py
Labels: bug-fix

#565 Fix #564
  nxc/protocols/smb/passpol.py
Labels: bug-fix

#568 [smb] Always delete output file
  nxc/protocols/smb/atexec.py
  nxc/protocols/smb/mmcexec.py
  nxc/protocols/smb/smbexec.py
  nxc/protocols/smb/wmiexec.py
Labels: bug-fix

#571 Bugfixes for py3.13
  .github/workflows/build-binaries.yml
  .github/workflows/build-zipapps.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  nxc/logger.py
  poetry.lock
Labels: bug-fix

#575 Refactored powershell_history module to fix case sensitivity
  nxc/modules/powershell_history.py
Labels: bug-fix

#576 Fix ASCII Art
  nxc/cli.py
Labels: bug-fix

#445 [SMB] Add the --qwinsta and --tasklist options
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
Labels: enhancement
