Repository Pennyw0rth/NetExec, pull requests merged in 2025-03, with the labels that each got.

#583 NFS escape to root fs
  nxc/protocols/nfs.py
  nxc/protocols/nfs/proto_args.py
Labels: enhancement, bug-fix

#584 Small bug fixes for NFS
  nxc/protocols/nfs.py
Labels: bug-fix

#570 Add support for latest Veeam version and add description to cred output
  nxc/data/veeam_dump_module/veeam_dump_mssql.ps1
  nxc/data/veeam_dump_module/veeam_dump_postgresql.ps1
  nxc/modules/veeam.py
Labels: enhancement, bug-fix

#588 Fix NFS issues when share is not listable
  nxc/protocols/nfs.py
Labels: bug-fix

#464 Create remote-uac.py
  nxc/modules/remote-uac.py
Labels: new module

#591 Catch ldap error if host is not reachable
  nxc/protocols/ldap.py
Labels: bug-fix

#574 Fix Poetry 2.1+ compatibility in `pyproject.toml`
  .github/workflows/test.yml
  nxc/cli.py
  poetry.lock
  pyproject.toml
Labels: documentation

#579 Remove pywerview dependency
  nxc/modules/group-mem.py
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
  nxc/protocols/smb/samrfunc.py
  poetry.lock
  pyproject.toml
Labels: enhancement, dependencies

#594 Use host IP for DNS resolution in asreproast function if kdcHost not specified
  nxc/protocols/ldap.py
  nxc/protocols/ldap/kerberos.py
Labels: bug-fix

#601 Revert #411 due to connection issues (#479)
  nxc/protocols/smb.py
Labels: bug-fix

#597 Several smaller bug fixes
  nxc/modules/get-unixUserPassword.py
  nxc/modules/get-userPassword.py
  nxc/modules/wcc.py
  nxc/parsers/ldap_results.py
  nxc/protocols/ldap.py
  nxc/protocols/nfs.py
  nxc/protocols/nfs/proto_args.py
  nxc/protocols/smb.py
Labels: bug-fix

#590 fix: check if an IP is being searched for when calling get_hosts
  nxc/database.py
  nxc/protocols/ftp/database.py
  nxc/protocols/mssql/database.py
  nxc/protocols/smb/database.py
  nxc/protocols/ssh/database.py
  nxc/protocols/winrm/database.py
Labels: bug-fix

#527 Added credential and host DB for LDAP protocol
  nxc/protocols/ldap.py
  nxc/protocols/ldap/database.py
  nxc/protocols/ldap/db_navigator.py
Labels: enhancement

#620 Fix spec file
  netexec.spec
Labels: bug-fix

#602 Export Users to a File
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
  nxc/protocols/smb/samruser.py
  tests/e2e_commands.txt
Labels: enhancement

#622 Improve WinSCP module
  nxc/modules/winscp.py
Labels: enhancement, bug-fix
