Repository Pennyw0rth/NetExec, pull requests merged in 2025-08, with the labels that each got.

#818 Rework atexec and -M schtask_as to rely on a single TSCH_EXEC class
  nxc/modules/schtask_as.py
  nxc/protocols/smb/atexec.py
Labels: refactor

#838 Add 'Warning' rule to linting
  nxc/cli.py
  nxc/database.py
  nxc/helpers/even6_parser.py
  nxc/helpers/misc.py
  nxc/helpers/ntlm_parser.py
  nxc/modules/add-computer.py
  nxc/modules/bitlocker.py
  nxc/modules/daclread.py
  nxc/modules/dfscoerce.py
  nxc/modules/dpapi_hash.py
  nxc/modules/enum_av.py
  nxc/modules/enum_links.py
  nxc/modules/enum_logins.py
  nxc/modules/eventlog_creds.py
  nxc/modules/get-info-users.py
  nxc/modules/ldap-checker.py
  nxc/modules/link_xpcmd.py
  nxc/modules/met_inject.py
  nxc/modules/mobaxterm.py
  nxc/modules/mremoteng.py
  nxc/modules/notepad++.py
  nxc/modules/notepad.py
  nxc/modules/petitpotam.py
  nxc/modules/pi.py
  nxc/modules/powershell_history.py
  nxc/modules/printerbug.py
  nxc/modules/rdcman.py
  nxc/modules/reg-winlogon.py
  nxc/modules/remove-mic.py
  nxc/modules/runasppl.py
  nxc/modules/schtask_as.py
  nxc/modules/scuffy.py
  nxc/modules/security-questions.py
  nxc/modules/shadowcoerce.py
  nxc/modules/shadowrdp.py
  nxc/modules/slinky.py
  nxc/modules/snipped.py
  nxc/modules/timeroast.py
  nxc/modules/vnc.py
  nxc/modules/wam.py
  nxc/nxcdb.py
  nxc/protocols/ftp.py
  nxc/protocols/ldap.py
  nxc/protocols/ldap/db_navigator.py
  nxc/protocols/ldap/resolution.py
  nxc/protocols/mssql/proto_args.py
  nxc/protocols/nfs.py
  nxc/protocols/smb.py
  nxc/protocols/smb/atexec.py
  nxc/protocols/smb/dpapi.py
  nxc/protocols/smb/proto_args.py
  nxc/protocols/smb/smbspider.py
  nxc/protocols/ssh/proto_args.py
  nxc/protocols/wmi.py
  pyproject.toml
  users
Labels: documentation

#844 Fix dpapi
  nxc/protocols/smb.py
Labels: bug-fix

#845 Revert "Merge pull request #729 from haytechy/refactor_SMBSpider"
  nxc/modules/spider_plus.py
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
  nxc/protocols/smb/smbspider.py
Labels: bug-fix

#824 Add --reg-sessions option to SMB protocol
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
Labels: enhancement

#855 Fix typo
  nxc/modules/whoami.py
Labels: documentation

#846 [SMB] Added new smb module to enumerate active network interfaces over SMB
  nxc/modules/enum_interfaces.py
  nxc/protocols/smb.py
  tests/e2e_commands.txt
Labels: enhancement

#721 Update schtask_as.py to help bypass detection
  nxc/modules/schtask_as.py
  nxc/protocols/smb/atexec.py
Labels: enhancement

#856 add guest check on recon
  nxc/config.py
  nxc/data/nxc.conf
  nxc/protocols/smb.py
Labels: enhancement

#898 Fix aardwolf logging
  poetry.lock
Labels: bug-fix

#884 fix(printnightmare): do not exit thread on failure to bind so other modules can run
  nxc/modules/printnightmare.py
Labels: bug-fix

#875 fix(dc_list): disable automatic configuration of DNS so we can point it to the target
  nxc/protocols/ldap.py
Labels: bug-fix

#901 Fix 879
  nxc/modules/pre2k.py
Labels: bug-fix

#904 Unnecessary file
  users
Labels: bug-fix

#830 Fix poetry run pytest & adding tests to ntds-dump-raw module
  tests/e2e_commands.txt
  tests/test_smb_database.py
Labels: bug-fix

#885 display group description for --groups
  nxc/protocols/ldap.py
Labels: enhancement

#866 Remove efsr_spray module, superceded by simply using EPM map on the EFS interface
  nxc/modules/coerce_plus.py
  nxc/modules/efsr_spray.py
Labels: enhancement

#877 Add ldap pass-pol option #868
  nxc/helpers/misc.py
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
  nxc/protocols/smb/passpol.py
  tests/e2e_commands.txt
Labels: enhancement
