Repository Pennyw0rth/NetExec, pull requests merged in 2025-09, with the labels that each got.

#907 Updated schtasks_as.py to control if output will be provided
  nxc/modules/schtask_as.py
Labels: enhancement

#586 New module: SCCM enumeration on DP and PSS with winreg
  nxc/modules/sccm-recon6.py
Labels: new module

#905 [New Module] CVE 2025 33073
  nxc/modules/ntlm_reflection.py
  tests/e2e_commands.txt
Labels: new module

#909 Fix MAQ module crash
  nxc/modules/maq.py
Labels: bug-fix

#916 Enforce that category is one of the enums
  nxc/loaders/moduleloader.py
Labels: bug-fix

#887 fix(enum_ca): properly return false if theres an error with fetchList
  nxc/modules/enum_ca.py
Labels: bug-fix

#938 Striped
  nxc/protocols/smb.py
Labels: bug-fix
