Repository Pennyw0rth/NetExec, pull requests merged in 2025-01, with the labels that each got.

#476 Improve LDAP dc-list flag
  nxc/protocols/ldap.py
Labels: enhancement

#524 ssh: allow for putting and getting files
  nxc/protocols/ssh.py
  nxc/protocols/ssh/proto_args.py
  tests/e2e_commands.txt
Labels: enhancement

#530 fix connection issue with socks ldap
  nxc/protocols/ldap.py
Labels: bug-fix

#531 Refactor ssh
  nxc/protocols/ssh.py
Labels: bug-fix, refactor

#533 add certificate authentication aka pass-the-cert
  .github/workflows/test.yml
  nxc/cli.py
  nxc/connection.py
  nxc/helpers/pfx.py
  nxc/protocols/ldap.py
Labels: enhancement

#534 switch default conn from smbv1 to smbv3
  nxc/modules/enum_av.py
  nxc/protocols/smb.py
Labels: bug-fix

#538 Fix spec file
  netexec.spec
  poetry.lock
  pyproject.toml
Labels: bug-fix, dependencies

#379 Add dpapi hash module based on the work of @fist0urs
  nxc/modules/dpapi_hash.py
  tests/e2e_commands.txt
Labels: new module
