Repository Pennyw0rth/NetExec, pull requests merged in 2025-04, with the labels that each got.

#625 smb: Prevent infinite loops handling an unknown error retrieving command output
  nxc/protocols/smb/atexec.py
  nxc/protocols/smb/mmcexec.py
  nxc/protocols/smb/smbexec.py
  nxc/protocols/smb/wmiexec.py
Labels: bug-fix

#450 [SMB] Add the recent_files module
  nxc/modules/recent_files.py
Labels: new module

#628 Fix left handside indent from exec output
  .github/workflows/lint.yml
  nxc/modules/recent_files.py
  nxc/protocols/smb.py
Labels: bug-fix

#633 SMB DPAPI Now Store Results, Issue #632
  nxc/first_run.py
  nxc/protocols/smb.py
Labels: enhancement

#636 Fix Kerberos Login While Using --use-kcache
  nxc/protocols/smb.py
Labels: bug-fix

#637 Fix ldap hash auth with signing enforced
  nxc/protocols/ldap.py
Labels: bug-fix

#639 Fix encoding issue in get-desc-user
  nxc/modules/get-desc-users.py
Labels: bug-fix

#638 Catch rpc error nca_s_op_rng_error when method is not implemented
  nxc/protocols/smb.py
Labels: bug-fix

#471 Update ldap.py for parse_result_attributes
  nxc/protocols/ldap.py
  nxc/protocols/ldap/proto_args.py
Labels: enhancement, bug-fix

#640 Add read principal to GMSA
  nxc/protocols/ldap.py
Labels: enhancement

#642 Add sid parsing directly to the ldap attribute parser
  nxc/parsers/ldap_results.py
  nxc/protocols/ldap.py
Labels: enhancement

#643 Add CODENAME for release v1.4.0
  nxc/cli.py
Labels: enhancement, good first issue

#650 fix: Refactor output file path construction in SMB protocol
  nxc/protocols/smb.py
Labels: bug-fix

#660 Added more AV Signatures
  nxc/modules/enum_av.py
Labels: enhancement

#658 Update database.py
  nxc/protocols/smb/database.py
Labels: bug-fix

#663 Fix bunch of stuff from ippsec and 0xdf writeup for vintage box
  nxc/protocols/ldap.py
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
  nxc/protocols/winrm.py
  poetry.lock
Labels: enhancement, bug-fix

#665 Fix pfx output path on windows
  nxc/helpers/pfx.py
Labels: bug-fix

#667 Fix authentication with an empty domain
  nxc/connection.py
  nxc/protocols/mssql.py
Labels: bug-fix

#669 Update pylnk3 to remove debug print
  poetry.lock
  pyproject.toml
Labels: bug-fix
