Repository Pennyw0rth/NetExec, pull requests merged in 2025-06, with the labels that each got.

#724 Add error handling if we can't mount share with --ls
  nxc/protocols/nfs.py
Labels: bug-fix

#561 new module: smb > presence
  nxc/modules/change-password.py
  nxc/modules/presence.py
Labels: new module

#649 Refactoring nxc path and adding support for XDG Base Directory - addressing issue #558
  nxc/config.py
  nxc/context.py
  nxc/first_run.py
  nxc/helpers/logger.py
  nxc/loaders/protocolloader.py
  nxc/modules/backup_operator.py
  nxc/modules/enum_dns.py
  nxc/modules/get-network.py
  nxc/modules/get_netconnections.py
  nxc/modules/keepass_trigger.py
  nxc/modules/spider_plus.py
  nxc/modules/user-desc.py
  nxc/netexec.py
  nxc/paths.py
  nxc/protocols/ldap.py
  nxc/protocols/rdp.py
  nxc/protocols/smb/atexec.py
  nxc/protocols/smb/mmcexec.py
  nxc/protocols/smb/wmiexec.py
  nxc/protocols/ssh/database.py
  nxc/protocols/vnc.py
  nxc/protocols/winrm.py
  nxc/protocols/wmi.py
Labels: enhancement, bug-fix

#493 Add new SMB module to extract GPO deployed privilege assignments
  nxc/modules/gpp_privileges.py
Labels: new module

#718 Add efsr_spray module
  nxc/modules/efsr_spray.py
Labels: new module

#737 Fix dns resolution when finding 2025 dc
  nxc/modules/badsuccessor.py
Labels: bug-fix

#455 New module: AWS Credentials Finder
  nxc/modules/aws-credentials.py
  nxc/protocols/winrm.py
Labels: new module, Waiting for response

#739 Fix function to check if hosts is a dc or not
  nxc/protocols/smb.py
Labels: bug-fix

#743 Fix conn reset error on windows if dc doesnt have tls cert
  nxc/protocols/ldap.py
Labels: bug-fix

#745 Fix #744
  nxc/protocols/ldap.py
Labels: bug-fix

#719 Add Kerberoasting support with no-preauth user
  nxc/connection.py
  nxc/protocols/ldap.py
  nxc/protocols/ldap/kerberos.py
  nxc/protocols/ldap/proto_args.py
Labels: enhancement

#765 fix hashcat/John format for TGS-REP
  nxc/protocols/ldap/kerberos.py
Labels: bug-fix
