Repository Pennyw0rth/NetExec, pull requests merged in 2025-05, with the labels that each got.

#512 New change-password module.
  nxc/modules/change-password.py
  nxc/protocols/smb.py
  tests/e2e_commands.txt
Labels: new module

#662 remove old server code unused
  netexec.spec
  nxc/cli.py
  nxc/connection.py
  nxc/logger.py
  nxc/modules/example_module.py
  nxc/modules/wcc.py
  nxc/netexec.py
  nxc/protocols/smb.py
  nxc/servers/__init__.py
  nxc/servers/smb.py
Labels: refactor

#681 Add a check if the database scheme contains the unique attribute
  nxc/protocols/smb/database.py
Labels: bug-fix

#682 Disable signing in LDAP temporarily
  nxc/protocols/ldap.py
Labels: bug-fix

#686 Automatically preserve state of "advanced options" on the target
  nxc/modules/link_enable_xp.py
  nxc/modules/link_xpcmd.py
Labels: bug-fix

#463 Add option to --spider and add recyclebin.py module
  nxc/modules/get_netconnections.py
  nxc/modules/recyclebin.py
  nxc/modules/veeam.py
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
  nxc/protocols/smb/smbspider.py
Labels: new module

#557 new module: mssql > enable_cmdshell
  nxc/modules/enable_cmdshell.py
  nxc/modules/link_enable_cmdshell.py
Labels: new module

#694 fix(ntlm): include server hostname in Workstation field of Authentication
  nxc/protocols/winrm.py
Labels: bug-fix

#696 Fix winrm database logic
  nxc/protocols/winrm.py
  nxc/protocols/winrm/database.py
Labels: bug-fix

#452 eventlog_creds Module
  nxc/helpers/even6_parser.py
  nxc/modules/eventlog_creds.py
Labels: new module

#695 Updated whoami and find-computer modules
  nxc/modules/find-computer.py
  nxc/modules/whoami.py
Labels: enhancement

#699 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#670 Fix ldap simple auth with base object
  nxc/protocols/ldap.py
Labels: bug-fix

#691 update ntdsutil.py to behave like --ntds
  nxc/modules/ntdsutil.py
Labels: bug-fix

#703 Fix logging port and also update the port when switching to LDAPS
  nxc/connection.py
  nxc/protocols/ldap.py
Labels: bug-fix

#705 Check for win server 2025 instead of DFL 2025
  nxc/modules/badsuccessor.py
Labels: bug-fix

#671 Fix hostname info if no ntlm and not resolution
  nxc/helpers/misc.py
  nxc/protocols/ldap/resolution.py
  nxc/protocols/smb.py
Labels: bug-fix

#664 Make nxc compatible with bloodhound-ce zip
  nxc/config.py
  nxc/data/nxc.conf
  nxc/helpers/misc.py
  nxc/protocols/ldap.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#707 Switch impacket branch to Pennyw0rth fork
  poetry.lock
  pyproject.toml
Labels: bug-fix, dependencies

#709 Ldap checker removal
  nxc/modules/ldap-checker.py
  nxc/protocols/ldap.py
  nxc/protocols/ldap/db_navigator.py
  poetry.lock
  pyproject.toml
  tests/e2e_commands.txt
Labels: enhancement
