Repository Pennyw0rth/NetExec, pull requests merged in 2025-07, with the labels that each got.

#766 Update wcc.py
  nxc/modules/wcc.py
Labels: documentation

#767 Fix winrm's ps_execute() to return output
  nxc/protocols/winrm.py
Labels: bug-fix

#772 Only display success message if accounts found
  nxc/modules/pre2k.py
Labels: bug-fix

#735 Image size improvements and pinned Netexec version
  Dockerfile
Labels: installation

#774 Update bitlocker.py - Corrected BitLocker EncryptionMethods
  nxc/modules/bitlocker.py
Labels: bug-fix

#777 Patch --qwinsta --tasklist stack trace
  nxc/protocols/smb.py
Labels: bug-fix

#784 setRemoteName to avoid Kerberos SPN resolution error in rid_brute
  nxc/protocols/smb.py
Labels: bug-fix

#787 Patches the --filter-shares so that it correctly finds READ,WRITE perm
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
Labels: bug-fix

#769 Add get-info-users module
  nxc/modules/get-info-users.py
  tests/e2e_commands.txt
Labels: new module

#795 add huge disclaimer to issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#794 docs: add deprecation change type and clarify e2e tests checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#808 Fix veeam script if there is no salt reg key
  nxc/modules/veeam.py
Labels: bug-fix

#800 Slinky set lnk target
  nxc/modules/slinky.py
Labels: bug-fix

#811 Add ldap parsing to daclread
  nxc/modules/daclread.py
  nxc/protocols/ldap.py
Labels: bug-fix

#468 Add raw-ntds-copy module
  nxc/connection.py
  nxc/data/ntds-dump-raw/ntds-dump-raw.ps1
  nxc/modules/ntds-dump-raw.py
  nxc/protocols/smb.py
Labels: new module

#820 Refactor WMI protocol execution
  nxc/protocols/wmi.py
  nxc/protocols/wmi/proto_args.py
  nxc/protocols/wmi/wmiexec.py
  nxc/protocols/wmi/wmiexec_event.py
Labels: bug-fix, refactor

#821 Add WMI to ntds_dump_raw module
  nxc/modules/ntds-dump-raw.py
Labels: enhancement

#828 Add TARGET option to ntds-dump-raw to dump LSA/SAM hashes
  nxc/modules/ntds-dump-raw.py
Labels: enhancement

#729 Refactor smb spider
  nxc/modules/spider_plus.py
  nxc/protocols/smb.py
  nxc/protocols/smb/proto_args.py
  nxc/protocols/smb/smbspider.py
Labels: enhancement, tested, reviewed code, refactor
